CREATE TABLE   HOBBY2 
   (	"HOBBYID" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"LOCATION" VARCHAR2(100)
   )   


SELECT * FROM  HOBBY

SELECT CONTENT  FROM HOBBY 

SELECT  LOCATION  , CONTENT  FROM HOBBY 


CREATE TABLE "HR"."PRODUCT2" 
   (	"ID" VARCHAR2(100), 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"PRICE" NUMBER(38,0)
   )
   
 ALTER TABLE PRODUCT2 ADD PRIMARY KEY (ID); -- 기존 테이블 컬럼에 pk추가
 
 INSERT INTO "MEMBER" VALUES ('200','100','park','011') -- 기존테이블에  컬럼추가
 
 
 SELECT * FROM "MEMBER" -- 전체 테이블 출력 
 
 SELECT * FROM "MEMBER" WHERE ID ='100' -- id가 100인 모든 컬럼 출력
 
 SELECT ID  FROM "MEMBER" WHERE ID ='100' --id가 100인 id컬럼
 
 SELECT ID AS 아이디, NAME FROM "MEMBER" WHERE  ID ='100'
 
 SELECT tel FROM "MEMBER" WHERE NAME='song'-- song의 tel 정보
 
 UPDATE "MEMBER" SET NAME ='kim' WHERE ID ='100'-- ID가 100인 
 
 DELETE FROM  "MEMBER" WHERE id='100' --member에서 id값이 100인 컬럼 삭제
 
 DELETE FROM  "MEMBER" WHERE tel='011'--member에서 tel값이 011인 컬럼 삭제
 
 SELECT * FROM "MEMBER" WHERE id ='200' AND tel='011'
 
SELECT * FROM "MEMBER" ORDER BY id -- 오름차순

SELECT * FROM "MEMBER" ORDER BY id DESC -- 내림차순

 
 
 -- product 테이블 생성
 CREATE TABLE "HR"."PRODUCT" 
   (	"ID" VARCHAR2(200), 
	"NAME" VARCHAR2(200), 
	"CONTENT" VARCHAR2(200), 
	"PRICE" VARCHAR2(200),
	"COMPANY" VARCHAR2(200),
	"IMG" VARCHAR2(200)
   )
   
 SELECT * FROM PRODUCT ORDER BY PRICE DESC -- 내림차순 
 
 SELECT id, NAME ,CONTENT FROM PRODUCT ORDER BY COMPANY 
 
 SELECT NAME , PRICE  FROM PRODUCT WHERE id='100'
 
 SELECT NAME, COMPANY FROM PRODUCT WHERE PRICE ='5000' 
 
SELECT NAME, IMG FROM PRODUCT WHERE ID='100'AND PRICE ='1000'
  
SELECT COMPANY, NAME FROM PRODUCT WHERE COMPANY  ='c100'
 
SELECT NAME, PRICE FROM PRODUCT WHERE COMPANY  = 'c100' OR COMPANY = 'c200'

-- SELECT NAME, PRICE FROM PRODUCT WHERE COMPANY  IN ('c100','c200')

UPDATE "PRODUCT" SET CONTENT ='품절' WHERE PRICE ='5000'

UPDATE "PRODUCT" SET IMG ='o.png' , PRICE ='10000' WHERE ID IN ('100','102')

SELECT  * FROM PRODUCT 

UPDATE PRODUCT SET COMPANY ='apple', NAME ='appleshoes' WHERE ID ='101'

DELETE FROM  "PRODUCT" WHERE NAME ='shoes1' OR ID ='107' 

DELETE FROM  "PRODUCT" WHERE COMPANY ='c100'

DELETE FROM "PRODUCT"

DROP TABLE "PRODUCT"



CREATE TABLE "REPLY"(
 	ID VARCHAR2(100) PRIMARY KEY,
 	ORIID VARCHAR2(100),
 	CONTENT VARCHAR2(100),
 	WRITER VARCHAR2(100)  
)
  
   




 
 
 
 